- name: Install Nginx Repository
  command: rpm -Uivh --replacepkgs http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm

- name: install nginx
  yum: name=nginx state=latest

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
  notify: restart nginx

- name: Copy nginx default configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf mode=0644
  notify: restart nginx

- name: Automatic load when boot
  command: systemctl enable nginx.service

- name: start nginx
  command: systemctl start nginx.service
